/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  theory: [
    "introduction",
    {
      type: "category",
      label: "Alfred's Essentials of Music Theory",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Book 1",
          link: {
            type: "generated-index",
          },
          items: [
            {
              type: "category",
              label: "Unit 1",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-1/unit-1",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 2",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-2/unit-2",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 3",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-3/unit-3",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 4",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-4/unit-4",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 5",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-5/unit-5",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 6",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-1/unit-6/unit-6",
              },
              items: [],
            },
          ],
        },
        {
          type: "category",
          label: "Book 2",
          link: {
            type: "generated-index",
          },
          items: [
            {
              type: "category",
              label: "Unit 7",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-7/unit-7",
              },
              items: [
                "alfreds-essentials-of-music-theory/book-2/unit-7/tetrachords-major-scales",
                "alfreds-essentials-of-music-theory/book-2/unit-7/the-sharp-scales",
                "alfreds-essentials-of-music-theory/book-2/unit-7/the-flat-scales",
                "alfreds-essentials-of-music-theory/book-2/unit-7/key-signatures-the-sharp-keys",
                "alfreds-essentials-of-music-theory/book-2/unit-7/key-signatures-the-flat-keys",
              ],
            },
            {
              type: "category",
              label: "Unit 8",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-8/unit-8",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 9",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-9/unit-9",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 10",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-10/unit-10",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 11",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-11/unit-11",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 12",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-2/unit-12/unit-12",
              },
              items: [],
            },
          ],
        },
        {
          type: "category",
          label: "Book 3",
          link: {
            type: "generated-index",
          },
          items: [
            {
              type: "category",
              label: "Unit 13",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-13/unit-13",
              },
              items: [
                "alfreds-essentials-of-music-theory/book-3/unit-13/triads-first-inversion",
              ],
            },
            {
              type: "category",
              label: "Unit 14",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-14/unit-14",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 15",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-15/unit-15",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 16",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-16/unit-16",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 17",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-17/unit-17",
              },
              items: [],
            },
            {
              type: "category",
              label: "Unit 18",
              link: {
                type: "doc",
                id: "alfreds-essentials-of-music-theory/book-3/unit-18/unit-18",
              },
              items: [],
            },
          ],
        },
      ],
    },
    {
      type: "category",
      label: "Concert Choir",
      link: {
        type: "doc",
        id: "concert-choir/concert-choir",
      },
      collapsed: false,
      items: [
        {
          type: "category",
          label: "Unit 1: Clefs, staff, lines + spaces, intro to sheet music",
          link: { type: "doc", id: "concert-choir/unit-1/unit-1" },
          items: [
            "concert-choir/unit-1/the-staff",
            "concert-choir/unit-1/music-notes-clefs",
          ],
        },
      ],
    },
    "singing-tips",
    "additional-resources",
    "how-to-contribute",
  ],
};

module.exports = sidebars;
