/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  theory: [
    'introduction',
    {
      type: 'category',
      label: "Alfred's Essentials of Music Theory",
      link: {
        type: 'generated-index',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Book 2',
          link: {
            type: 'generated-index'
          },
          items: [
            {
              type: 'category',
              label: 'Unit 7',
              link: {type: 'doc', id: 'alfreds-essentials-of-music-theory/book-2/unit-7/unit-7'},
              items: [
                'alfreds-essentials-of-music-theory/book-2/unit-7/tetrachords-major-scales',
                'alfreds-essentials-of-music-theory/book-2/unit-7/the-sharp-scales',
                'alfreds-essentials-of-music-theory/book-2/unit-7/the-flat-scales',
                'alfreds-essentials-of-music-theory/book-2/unit-7/key-signatures-the-sharp-keys',
                'alfreds-essentials-of-music-theory/book-2/unit-7/key-signatures-the-flat-keys',
              ]
            },
          ]
        }
      ],
    },
    {
      type: 'category',
      label: 'Concert Choir',
      link: {
        type: 'doc', id: 'concert-choir/concert-choir',
      },
      collapsed: false,
      items: [
        {
          type: 'category',
          label: 'Unit 1: Clefs, staff, lines + spaces, intro to sheet music',
          link: {type: 'doc', id: 'concert-choir/unit-1/unit-1'},
          items: [
            'concert-choir/unit-1/the-staff',
            'concert-choir/unit-1/music-notes-clefs',
          ]
        },
      ],
    },
    'singing-tips',
    'additional-resources',
    'how-to-contribute',
  ],
};

module.exports = sidebars;
